### ISSUE TITLE
Game No Longer Loads With Community Mod

### ISSUE THREAD

**Issue by thehrmmoose** [tashcan/bob#13] opened 2024-02-06 12:23 UTC
After the most recent patch on Feb 6 2024, the game no longer loads when using the community mod.  It crashes to desktop upon loading the game.

**Comment by not-so-important** [comment] 2024-02-06 12:34
I confirm that the game doesn't start after the Feb 6 patch with the community mod any more ...

**Comment by theonlyway** [comment] 2024-02-06 12:37
Here is the crash log. I removed the mods starting logs since it basically contains the config values as well as the spocks.club sync token and doesn't appear to be related to the actual crash.
[Player.log](https://github.com/tashcan/bob/files/14179589/Player.log)

**Comment by theonlyway** [comment] 2024-02-06 12:38
Here is the crash log. Seems it's having issues reading some values
[Player.log](https://github.com/tashcan/bob/files/14179606/Player.log)

**Comment by aw-tech** [comment] 2024-02-06 12:58
Same here ..

**Comment by MartyMacGyver** [comment] 2024-02-06 13:00
FYI, if you have the same problem but _no new information to add_, click the `Subscribe` button to the right to get updates instead.

**Comment by netniV** [comment] 2024-02-06 13:26
I believe that I tracked the issue to:
![image](https://github.com/tashcan/bob/assets/9052188/53620bcf-3565-4c09-b5b2-734ed3623a49)

This is part of a third party library the mod uses:
![image](https://github.com/tashcan/bob/assets/9052188/28d17954-d400-4438-aaf4-a7f43b18470b)
![image](https://github.com/tashcan/bob/assets/9052188/45608dcb-f057-4bb1-b9d8-a650396d28ec)

However, I'm struggling right now to see if there's a specific update to match Unity 2021.3.23 that someone kindly mentioned Scopely seem to have updated the game to.

For now, the only solution I have until a fix is found is to rename the mod to .old and use the game without it.

**Comment by netniV** [comment] 2024-02-06 13:37
Yes, that was.  I clocked that they confirmed the Unity engine update.  That really should have been announced by them before hand ... but would have had no way to test it anyway as I'm not in their NDA program etc.

**Comment by varneyb** [comment] 2024-02-06 14:18
> However, I'm struggling right now to see if there's a specific update to match Unity 2021.3.23 that someone kindly mentioned Scopely seem to have updated the game to.
> 
> For now, the only solution I have until a fix is found is to rename the mod to .old and use the game without it.

Hopefully a solution can be found. I find the game almost unusable on the PC without the mod.

**Comment by mrbv1** [comment] 2024-02-06 18:03
rolling back to v4.3 will allow you to load the game, but still has random issues where it will crash here and there

**Comment by STFCTolstoy** [comment] 2024-02-06 18:33
> rolling back to v4.3 will allow you to load the game, but still has random issues where it will crash here and there

For me I'm crashing every time I attempt to chat. Particularly when I hit certain bound keys like C

**Comment by mrbv1** [comment] 2024-02-06 18:37
> > rolling back to v4.3 will allow you to load the game, but still has random issues where it will crash here and there
> 
> For me I'm crashing every time I attempt to chat. Particularly when I hit certain bound keys like C

Yeah, it seems to be chat related for me as well, but it's weird. it seems to be happening when 'R' or 'F' keys are pressed, but only when my main view is in system or galaxy view. 

I'm still fiddling around, but either way, it's lame. Hopefully someone a lot smarter than I am can figure out a fix quickly

**Comment by tashcan** [comment] 2024-02-06 20:00
Please test, which should fix the issue https://github.com/tashcan/bob/releases/tag/v0.5.4-u2021-t1

**Comment by mrbv1** [comment] 2024-02-06 20:16
> Please test, which should fix the issue https://github.com/tashcan/bob/releases/tag/v0.5.4-u2021-t1

Loaded fine. So far so good. No crashes as previously encountered with chat. Will update if I come across any issues.

**Comment by tashcan** [comment] 2024-02-06 21:48
Closing as things seem to be working.

**Closed by tashcan** 2024-02-06 21:48 UTC
